### ISSUE TITLE
".5" volumes.

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack#10]
Sorry, I just realized I cannot reopen an issue when closed by admin. Here my report about the issue #7 :

Nothing.. just to be sure I deleted the whole folder and redownloaded it (2014-12-28), I should have attached a screenshot with the result.
Maybe it is because the ".5" is attached to the volume and not to the chapter? By the way these two files have no metadata parsed at all, the other are just fine.

![screenshot 2014-12-30 22 28 09](https://cloud.githubusercontent.com/assets/6177535/5583136/39998f12-9074-11e4-97c0-bcfffad7c2d8.png)

**Comment by Deathspike** [comment]
It's actually not a MangaRack.js bug; the ComicInfo.xml is written as expected.

It seems that ComicRack has an issue dealing with this kind of volume. I forwarded the bug to:

http://comicrack.cyolito.com/forum/10-bugs/38613-volume-15-is-not-recognized

Let's continue this there :)

**Comment by XellossMetallium** [comment]
@Deathspike I trust your judgment. Just to be precise I actually checked the comicinfo.xml before reporting.. in my case it is incomplete:

V1.5 1 has:

<?xml version="1.0"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <PageCount>50</PageCount>
  <Pages>
    <Page Image="0" ImageWidth="900" ImageHeight="1267" Type="FrontCover" />
    <Page Image="1" ImageWidth="3195" ImageHeight="1400" />
  </Pages>
</ComicInfo>

while c2 is like this:

<?xml version="1.0"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <PageCount>65</PageCount>
  <Pages>
    <Page Image="0" ImageWidth="900" ImageHeight="1267" Type="FrontCover" />
  </Pages>
</ComicInfo>

If my case is different it is very strange! Anyway when I manually corrected the entry in comicrack I noticed the lack of support too, so let's see if something happens on that side!

**Comment by Deathspike** [comment]
Can you post the XML again with tabs? This is the full XML I get for `Akame ga KILL! V01.5 #001.cbz`:

    <?xml version="1.0" encoding="utf-8"?>
    <ComicInfo>
      <Genre>Action, Comedy, Drama, Ecchi, Fantasy, Horror, Mystery, Psychological, Romance, Shounen, Supernatural, Tragedy</Genre>
      <Manga>YesAndRightToLeft</Manga>
      <Number>1</Number>
      <Penciller>Tetsuya Tashiro</Penciller>
      <Pages>
        <Page Key="000.jpg" Image="0" Type="FrontCover"/>
        <Page Key="001.jpg" Image="1"/>
        <Page Key="002.png" Image="2"/>
        <Page Key="003.png" Image="3"/>
        <Page Key="004.png" Image="4"/>
        <Page Key="005.png" Image="5"/>
        <Page Key="006.png" Image="6"/>
        <Page Key="007.png" Image="7"/>
        <Page Key="008.png" Image="8"/>
        <Page Key="009.png" Image="9"/>
        <Page Key="010.png" Image="10"/>
        <Page Key="011.png" Image="11"/>
        <Page Key="012.png" Image="12"/>
        <Page Key="013.png" Image="13"/>
        <Page Key="014.png" Image="14"/>
        <Page Key="015.png" Image="15"/>
        <Page Key="016.png" Image="16"/>
        <Page Key="017.png" Image="17"/>
        <Page Key="018.png" Image="18"/>
        <Page Key="019.png" Image="19"/>
        <Page Key="020.png" Image="20"/>
        <Page Key="021.png" Image="21"/>
        <Page Key="022.png" Image="22"/>
        <Page Key="023.png" Image="23"/>
        <Page Key="024.png" Image="24"/>
        <Page Key="025.png" Image="25"/>
        <Page Key="026.png" Image="26"/>
        <Page Key="027.png" Image="27"/>
        <Page Key="028.png" Image="28"/>
        <Page Key="029.png" Image="29"/>
        <Page Key="030.png" Image="30"/>
        <Page Key="031.png" Image="31"/>
        <Page Key="032.png" Image="32"/>
        <Page Key="033.png" Image="33"/>
        <Page Key="034.png" Image="34"/>
        <Page Key="035.png" Image="35"/>
        <Page Key="036.png" Image="36"/>
        <Page Key="037.png" Image="37"/>
        <Page Key="038.png" Image="38"/>
        <Page Key="039.png" Image="39"/>
        <Page Key="040.png" Image="40"/>
        <Page Key="041.png" Image="41"/>
        <Page Key="042.png" Image="42"/>
        <Page Key="043.png" Image="43"/>
        <Page Key="044.png" Image="44"/>
        <Page Key="045.png" Image="45"/>
        <Page Key="046.png" Image="46"/>
        <Page Key="047.png" Image="47"/>
        <Page Key="048.png" Image="48"/>
        <Page Key="049.jpg" Image="49"/>
      </Pages>
      <Series>Akame ga KILL!</Series>
      <Summary>Tatsumi is a fighter who, accompanied by his two childhood friends, sets off to the Capital in search of a way to make money to assist his poverty-stricken village. After being separated from his friends, Tatsumi not only fails to enlist in the army, but is swindled out of all his money. He is then taken in by a noble family who offer him help; after finding himself in a messy situation Tatsumi is rescued by a group of assassins known as Night Raid, and is invited to join their ranks. Composed of the swordswoman Akame, a young woman armed with a huge pair of scissors named Sheele, the string manipulator Lubbock, the armored warrior Bulat, the sniper Mine, the beast fighter Leone and their leader Najenda, Night Raid is also part of the revolutionary forces assembled to overthrow Prime Minister Honest, who manipulates the young emperor for his and his men's personal gain, leading the rest of the nation to poverty and strife.
    
    
    
    Prequel:
    
    &gt; Akame ga Kill! Zero 
    ( http://www.batoto.net/comic/_/comics/akame-ga-kill-zero-r9902 )</Summary>
      <Title>Kill the Blackness</Title>
      <Volume>1.5</Volume>
      <Writer>Takahiro</Writer>
    </ComicInfo>

**Comment by XellossMetallium** [comment]
https://dl.dropboxusercontent.com/u/37448634/ComicInfo.xml

Here you go, V1.5 c001. Sorry, I don't know the tag to put the code in a different layer. :)

**Comment by Deathspike** [comment]
That seems weird. The `ComicInfo.xml` is not complete at all. It even shows the `PageCount` to be 50 but there is nothing else in the meta-data file? Can you post the entire CBZ as it rolls out of MRjs?

**Comment by XellossMetallium** [comment]
Sure, it's 20mb so it will take a little to upload :)

**Comment by Deathspike** [comment]
I cannot seem to reproduce this. Can you post some OS information?

Windows version, x86 or x64, what culture (language settings), which node version (`node --version`)?

I seem to get this, you see...

    <?xml version="1.0" encoding="utf-8"?>
    <ComicInfo>
      <Genre></Genre>
      <Number>0</Number>
      <Penciller>MOCHIZUKI Jun</Penciller>
      <Pages>
        <Page Key="000.jpg" Image="0" Type="FrontCover"/>
        <Page Key="001.jpg" Image="1"/>
        <Page Key="002.jpg" Image="2"/>
        <Page Key="003.jpg" Image="3"/>
        <Page Key="004.jpg" Image="4"/>
        <Page Key="005.jpg" Image="5"/>
        <Page Key="006.jpg" Image="6"/>
        <Page Key="007.jpg" Image="7"/>
        <Page Key="008.jpg" Image="8"/>
        <Page Key="009.jpg" Image="9"/>
        <Page Key="010.jpg" Image="10"/>
        <Page Key="011.jpg" Image="11"/>
        <Page Key="012.jpg" Image="12"/>
        <Page Key="013.jpg" Image="13"/>
        <Page Key="014.jpg" Image="14"/>
        <Page Key="015.jpg" Image="15"/>
        <Page Key="016.jpg" Image="16"/>
        <Page Key="017.jpg" Image="17"/>
        <Page Key="018.jpg" Image="18"/>
        <Page Key="019.jpg" Image="19"/>
      </Pages>
      <Series>Pandora Hearts ~odds and ends~</Series>
      <Summary>The one and only Pandora Hearts artbook &lt;3</Summary>
      <Title>Artbook: odds and ends Part 1</Title>
      <Volume>60.1</Volume>
      <Writer>MOCHIZUKI Jun</Writer>
    </ComicInfo>

**Comment by XellossMetallium** [comment]
Let's see.. Windows 7x64, Italian, node v.0.10.35.
I just formatted my pc, so I cannot guarantee that the node version is the same. To be sure I'll try to download again these chapters, I'll report soon!

**Comment by Deathspike** [comment]
I'm going through the bugs that I can deal with right now and what goes into the next big version, and surprisingly, I completely missed the last response on this one! I know you've been using MR actively, has this ever occurred again? Do you still struggle with this? Learned anything new for reproducing purposes?

**Comment by XellossMetallium** [comment]
Well, the problem was still there a couple of months ago (I tried to redownload Akame and Pandora after a fresh windows install out of curiosity).. yet since it happened only with the specials of these two series, I have to admit that I simply fixed the issue manually and forgot about it..  
Tomorrow I'll try to make a separate list for the two titles.. If by doing so I manage to bypass #32 I will experiment more and report about this issue!

**Comment by Deathspike** [comment]
I'm filing this under "Mysterious and weird". Please re-open if there is another lead in this problem :)
