### ISSUE TITLE
Improvements in Batoto metadata (scanlator, reading direction, version?)

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack#2]
Hi, here is the feature request.
Since batoto offers a well organized and high quality library, albeit smaller than other famous sites, sometimes some chapters are double posted. These chapters more often than not are from different scanlator groups, so downloading both of them and being able to differenciate each release is not pointless. "Group" is a tab which reports the scanlator group, so filling the proper metadata tag ("informazioni sulla scansione" below summary, in italian) in comicrack should be simple. 
I don't know if the same could (and if it would have sense at all) be done with the "version" of the chapter, to have the capters overwritten when a v2 or v3 is out. I think I recall that mangarack (at least in the previous incarnation) already has a way to deal with updates. I still don't understand the way it works, so I'll leave this here. :)
Moreover the option "manga, from left to right" could be made standard in comicrack metadata when the "type" tag in batoto is "manga" and not "manhwa".
Thanks,
Mario.

Update: another tag that shouldn't be too problematic ==> "completed/ongoing".

**Comment by XellossMetallium** [comment]
I just wanted to report something I just noticed, for when this issue will be adressed and before I forget it:
the "version" tag is usually added to the chapter number, in the form of: "[v2]" or "(v2)", but in a couple of cases, in particular in "Gate" (http://bato.to/comic/_/comics/gate-thus-the-jsdf-fought-there-r5353), the v2 for some reason was attacched at the beginning of the title (chapters 10 and 11). 
In fact this made it impossible for Mangarack to filter the "Read Online" title out, and the title right now is "v2 Read Online". 
I don't know if this is a frequent occurrence, but it should be noted. :)

**Comment by murraypaul** [comment]
I've done something a little like this in my local version.
I transfer the Batato group name to the ScanInformation tag in the ComicRack xml file, and have added a commandline filter to allow only certain groups to be retrieved.
This seems to work ok with comics with multiple release groups, where you want to pull out only one, but wouldn't help if you wanted to download all the different versions.

**Comment by XellossMetallium** [comment]
Now that I read again all the comments above I just noticed that I never come to understand how mangarack v4 treats (normally) multiple instances of the same chapter, like: new versions at the same time, two versions of different groups and a new version that replaces an older one... 

The group tag (apart from using it as filter) still has the open issue of the naming scheme.. that being solved I suppose (again, except the filter) that downloading multiple versions of the same chapter shouldn't go in contrast with the "leitmotiv" of mangarack v4, since this way the local folder would mirror even more precisely the provider. 

@murraypaul should the chosen scanlator "A" skip a chapter for some reason, the version of group "B" would be downloaded instead?

By the way, I gave up on my hard drive space years ago, so downloading all chapters (#48) or duplicate chapters (this issue) make no real difference for me.. at this point the more, the merrier!

**Comment by murraypaul** [comment]
I've just hit a situation where there are multiple groups each of which overlap with some of the others at one point or another, none of which go through the entire series. In order to be able to sort out and maintain the greatest amount of consistency across the files, I've just added the group name to the download file name, so that all files are downloaded, and I can then choose which to use.
It is the most consistent and predicable thing to do, but in most cases I think it will generate more files than people would probably want.

**Comment by Deathspike** [comment]
> Now that I read again all the comments above I just noticed that I never come to understand how mangarack v4 treats (normally) multiple instances of the same chapter, like: new versions at the same time, two versions of different groups and a new version that replaces an older one... 

It doesn't. *MangaRack* relies on *visible data* and infers information from that particular data set. That means it *cannot* detect when V01C01 was removed and replaced with a new V01C01. Earlier versions would rely on *hidden data* (the chapter identifier that you see in the URL in this case) and would therefore be capable of detecting new uploads replacing the older one (assuming there was no id reuse in the first place). But, the new guidelines for *MangaRack* explicitly deny relying on non-visible information for feature support. Whenever a provider goes and removes the *non visible* information, tools relying on it would stop working while *MangaRack* continues happily like an actual human. This may be paranoia for now, but at least we can guarantee consistency so long as a provider allows you to read chapters.

> The group tag (apart from using it as filter) still has the open issue of the naming scheme.. that being solved I suppose (again, except the filter) that downloading multiple versions of the same chapter shouldn't go in contrast with the "leitmotiv" of mangarack v4, since this way the local folder would mirror even more precisely the provider.

On providers where there is a difference between translation groups, this would make perfect sense. It would have to be enabled on a provider-level and require consistency (thus every entry *must* have a translation group name). We could use a name like `Series V01 #001 [Translator].cbz` which would make the mirrored folder capable of containing all translations. It would mean breaking backwards compatibility for Batoto, specifically. Similarly, we could opt-in to languages and add a prefix getting all the archives in that manner as well..

> It is the most consistent and predicable thing to do, but in most cases I think it will generate more files than people would probably want.

It is the most predictable to do, indeed. This would be an issue for those deprived of hard-disk space, but honestly, it's not *that* expensive to get a little more space in this day and age. Therefore I consider that point to be a little moot. On the other hand, we've always supported `ComicInfo.xml` for *ComicRack* support (which, for now, remains the main reading method for most of us), and I'm not sure how this would collide with its reading capabilities. Can it differ between translation groups? And does that also work on the mobile variants? When you go to "next chapter", you expect the next chapter, and not a different translation of the same chapter. These are issues that would have to be investigated.

**Comment by murraypaul** [comment]
> On providers where there is a difference between translation groups, this would make perfect sense. It would have to be enabled on a provider-level and require consistency (thus every entry must have a translation group name). We could use a name like Series V01 #001 [Translator].cbz which would make the mirrored folder capable of containing all translations. It would mean breaking backwards compatibility for Batoto, specifically. Similarly, we could opt-in to languages and add a prefix getting all the archives in that manner as well..

That is the naming convention I've implemented locally. I added a switch for whether to include the group name or not, which means it doesn't have to break backwards compatibility, you can switch it on only for those mangas you need it for.

> It is the most predictable to do, indeed. This would be an issue for those deprived of hard-disk space, but honestly, it's not that expensive to get a little more space in this day and age. Therefore I consider that point to be a little moot. On the other hand, we've always supported ComicInfo.xml for ComicRack support (which, for now, remains the main reading method for most of us), and I'm not sure how this would collide with its reading capabilities. Can it differ between translation groups? And does that also work on the mobile variants? When you go to "next chapter", you expect the next chapter, and not a different translation of the same chapter. These are issues that would have to be investigated.

There is a ScanInformation tag in the xml file where the data can be stored, so the files can be differentiated in ComicRack, but they would still show up as multiple chapters, and the user would have to manually uncheck the ones they didn't want, or use smart lists, to prevent multiple copies being synced to the mobile device and read in turn.

**Comment by XellossMetallium** [comment]
> It doesn't. MangaRack relies on visible data and infers information from that particular data set.


Yes, disregarding hidden data it is a minor issue.. actually reliying on scans more than actual copies of the work is a compromise by itself.. a typo or a little mistake in translation shouldn't be a big deal. It is still possible to refresh the library bit by bit periodically, to upgrade replaced chapters.

Speaking of new versions of a chapter, if the update is apparent on the visible level (like "v2" in the chapter), is this info still ignored? 
Just like the tag is filtered out, could a change in the "chapter number" field (this seems to be where usually they add the versioning, but I can't find any info about this in the guidelines https://bato.to/forums/topic/894-guide-to-uploading-editdeleteerrorsnotes/ *) trigger a new download of the chapter?
In other words:
V1 c1 (10mb) > v1 c1 (12mb) ==> ignored (the user should delete the file to update)
v1 c1 > v1 c1(v2) ==> force new download (maybe add version info in xml or filename)

*Oh, I just noticed something that could be relevant.. I'll report in a new issue.

> Can it differ between translation groups? And does that also work on the mobile variants? When you go to "next chapter", you expect the next chapter, and not a different translation of the same chapter.

About Comicrack reading experience.
The actual problem is that ComicRack does not support (I think) complex sorting rules, so chosing to sort by scanlator would work perfectly only as long as the scanlator is consistent.. Should group "Zeta" work on chapters 1-10 and group "Alfa" work on chapters 11-20 the order would be automatically be messed up... the only thing that comicrack seems to be able to do is to "remember" the previous sorting.. so if I sort first by chapter, then by (for example) number of pages, the chapters with "10 pages" will still be sorted by chapter... but this hardly solves all cases.

All that being said, reading on desktop will always require a bit of manual work (creating a smart list for sync to device or to filter out some group and so on)... 
What could solve (not perfectly) all problems would be something like "only show one entry for each chapter number" and, for android version "only sync one entry for each chapter number".. but only ComicRack dev could do something about that.


Lastly.. this is a bit selfish, but.. because of this Kindle Comic Converter feature: https://github.com/ciromattia/kcc/wiki/Manga-Cover-Database-support 
should the "group tag" become officially supported, I suggest to use a different (but related) field in comicrack.xml, like "Teams" instead of "ScanInformations". 
This should be consistent with the fact that Scaninformations is a "free" field, while "Teams" lines are added to the database... (I mean.. see the little diamond near "teams" field).

**Comment by murraypaul** [comment]
> Lastly.. this is also a bit selfish, but.. because of this Kindle Comic Converter feature: https://github.com/ciromattia/kcc/wiki/Manga-Cover-Database-support 
should the "group tag" become officially supported, I suggest to use a different (but related) field in comicrack.xml, like "Teams" instead of "ScanInformations". 
Moreover this should be consistent with the fact that Scaninformations is a "free" field, while "Teams" lines are added to the database... (I mean.. see the little diamond near "teams" field).

Pretty sure that the Teams field is intended to be used to list which superhero teams were involved in the issue, similar to the Characters field?

**Comment by XellossMetallium** [comment]
> Pretty sure that the Teams field is intended to be used to list which superhero teams were involved in the issue, similar to the Characters field?

Now that you said it... yes, you are probably right :o I have very few western comics (mostly graphic novels or not-superhero), so I never considered that possibility. 
To be honest I think that generic tags make a field just for the superhero team a bit redundant, so I will not retire my suggestion.. but obviously I wont complain in either case ;)

**Comment by Deathspike** [comment]
https://github.com/Deathspike/mangarack/issues/79
