### ISSUE TITLE
Version tag not filtered in rare unsupported cases

### ISSUE THREAD

**Issue by Deathspike** [Deathspike/mangarack#25]
@XellossMetallium reported in https://github.com/Deathspike/mangarack.js/issues/2#issuecomment-74097538:

> I just wanted to report something I just noticed, for when this issue will be adressed and before I forget it:
the "version" tag is usually added to the chapter number, in the form of: "[v2]" or "(v2)", but in a couple of cases, in particular in "Gate" (http://bato.to/comic/_/comics/gate-thus-the-jsdf-fought-there-r5353), the v2 for some reason was attacched at the beginning of the title (chapters 10 and 11).
In fact this made it impossible for Mangarack to filter the "Read Online" title out, and the title right now is "v2 Read Online".
I don't know if this is a frequent occurrence, but it should be noted. :)

**Comment by XellossMetallium** [comment]
Since the concept is the same I add it here: another case of unfiltered "Read Online".

http://bato.to/comic/_/comics/cross-x-regalia-r10243
Ch.16: Read Online [End]

**Comment by Deathspike** [comment]
This will go live with `4.0.5` or `4.1.0`.
