### ISSUE TITLE
Feature suggestion: Batoto "Following list" as download list

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack#36]
This came to mind while adapting my download list to the new standards and could be a nice thing to implement when the situation with the new version will be stable.

I don't know how are things for other users, but in my case when I first compiled my list for mangarack I kept (manually) synced my following list on batoto.. these would be the main points:
- since username and password are provided anyway.
- since almost all commands that would collide with "generalized" settings (like --output) are deprecated.
- since the following list should be available (I suppose, since at least an android app I occasionally use can fetch it) and should actually consist in a list of links to the various series pages.
- obviously if technically possible and worth the effort

It would be nice to be able to optionally fetch the following list from batoto and download the series listed there, without using a txt file.

This way the user could benefit of some sort of "indirect" graphic interface for mangarack, simply using the "Follow" button on the main site, making the experience more consistent (hopefully not colliding with the new approach of mangarack 4.0) between local reading and online reading. 
I.e. to subscribe to batoto rss feed and at the same time set mangarack to run once every X hours.

**Comment by Deathspike** [comment]
This sounds pretty cool! And this kind of idea is exactly why `4.x` uses *stdin* instead of a file. It's actually technically feasible to simply scrape a remote list and feed the list into the existing `mangarack-cli` application without requiring *any* modification in the *cli*.

I will have to look into where these user lists are located on batoto, kissmanga and mangafox (if the other two actually have their own lists, which I suspect they do). Or perhaps you'd be so kind to see if an account is needed, and what the HTTP address of each list will be?

**Comment by XellossMetallium** [comment]
Happy to see you like the idea!

Let's see.. for batoto the list is at this page: 
http://bato.to/myfollows . 
I don't see a way to make the list public (to have an unique link) nor a way to add customized lists.

For mangafox and kissmanga I just registered an account to check, so I could be wrong, but:

Mangafox has a bookmark feature with some default sublists:
http://mangafox.me/bookmark/?status=all 
and ?status=currentreading, ?status=onhold, ?status=completed ?status=plantoread
I don't see a way to create other lists.

Kissmanga seems to have just one list, like batoto, here:
http://kissmanga.com/BookmarkList

For all links the structure seems to be quite simple, with the list of direct links to the single serie page, but I suspect that all requires userid and password to access it.

**Comment by Deathspike** [comment]
https://github.com/Deathspike/mangarack/issues/79
