### ISSUE TITLE
Mangarack not working on :REverSAL

### ISSUE THREAD

**Issue by Mereck13579** [Deathspike/mangarack#39]
When I try to use mangarack on this : http://bato.to/comic/_/comics/reversal-r3877 it just starts and do nothing. I launched a packet capture and saw that nothing was done (not even DNS Query / HTTP Get), the record is just empty. I don't even get an error message like the other series when bato.to just doesn't respond.

mereck@Akigumo:~/mangarack$ mangarack-cli --component.core.batoto.username MyUser --component.core.batoto.password MyPassword http://bato.to/comic/_/comics/eg-maker-r12038
mangarack-cli (4.0.1)
Fetching EG Maker
Finished EG Maker (00:00:06)
mereck@Akigumo:~/mangarack$ mangarack-cli --component.core.batoto.username MyUser --component.core.batoto.password MyPassword http://bato.to/comic/_/reversal-r3877
mangarack-cli (4.0.1)

[Ctrl-C here after 5 minutes]

EDIT : 
Ok nevermind I found the source of the problem, I just copy pasted the link from a search query on bato.to (namely this : http://bato.to/search?name=reversal&name_cond=c) but didn't follow the link and http://bato.to/comic/_/reversal-r3877 redirects to http://bato.to/comic/_/comics/reversal-r3877
Might be worth it to make mangarack more tolerant to this, or at least print out an error message.

**Comment by Mereck13579** [comment]
Ok nevermind I found the source of the problem (and you might want to 'fix' that), I just copy pasted the link from a search query on bato.to (namely this : http://bato.to/search?name=reversal&name_cond=c) but didn't follow the link and http://bato.to/comic/_/reversal-r3877 redirects to http://bato.to/comic/_/comics/reversal-r3877
Might be worth it to make mangarack more tolerant to this, or at least print out an error message.

**Comment by Deathspike** [comment]
Dropping this issue after a massive amount on inactivity.

Since the library will soon take over, this point will become moot with its built-in search capabilities.

Please re-open if there are good arguments to make MR more tolerant anyway :+1:
