### ISSUE TITLE
Non-understandable error message on non-english series

### ISSUE THREAD

**Issue by Mereck13579** [Deathspike/mangarack#41]
I was trying to use mangarack on Aoki Hagane no Arpeggio (http://bato.to/comic/_/comics/aoki-hagane-no-arpeggio-r483) but I didn't notice that the series didn't feature english. When executing the usual command to use mangarack, I got the following error : 
Fetching Aoki Hagane no Arpeggio
Error: ENOENT: no such file or directory, scandir 'Aoki Hagane no Arpeggio'
    at Error (native)

At first I thought it was some kind of weird permission problem so I created the Aoki Hagane no Arpeggio folder manually and then re-execute the command : 
mangarack-cli (4.0.7)
Fetching Aoki Hagane no Arpeggio
Finished Aoki Hagane no Arpeggio (00:00:06)

At this point I went and check Bato.to only to notice that it was pulled out in English and was only available in Spanish.
It might be worth putting another error message in case this happens (also might be a good idea to have an option to allow Mangarack to download stuff in other language than English?)

**Comment by Deathspike** [comment]
Fixed in `4.0.8` / `4.1.0`
