### ISSUE TITLE
Sorting / Synchronizing problem with undefined volume number

### ISSUE THREAD

**Issue by Mereck13579** [Deathspike/mangarack#44]
I have some series that have some volume defined and some not ([bato.to/comic/_/comics/seitokai-yakuindomo-r1597](bato.to/comic/_/comics/seitokai-yakuindomo-r1597), [http://bato.to/comic/_/comics/its-not-my-fault-that-im-not-popular-r1054](http://bato.to/comic/_/comics/its-not-my-fault-that-im-not-popular-r1054)...). Mangarack fetches them without any problem and doesn't fill the volume number field for the chapters that aren't attached to a volume.
The problem is that Comicrack then decide to prioritize undefined volume number over defined ones, sorting them in a messy order. For example, for it's not my fault that i'm not popular, it goes like this : 
- chapter 0 (undefined volume)
- chapter 18, 18.5, 19... 93 (undefined volume)
- volume 1, chapter 1... 9, 9.5, 9.75
- volume 2, chapter 10, etc...

That wouldn't be that annoying if it didn't affect synchronizing with other devices as well (I'm mainly using an android tablet to read mangas). Since I want to have the last X unread chapter, it synchronize every "next" chapter, except it considers the same order of reading as the weird sorting order.

While I know Mangarack is not at fault (it's obviously because the chapters aren't properly tagged on batoto), I wonder if anything could be done in Mangarack. The only workaround I found so far was to manually tag all those undefined volume with a high enough value (like 99).

**Comment by Deathspike** [comment]
You can use a different sorting in ComicRack. Set it to 'Order By Number' and the sorting should be good. At least, that option is available on Android devices, but iOS devices may be different (I haven't got one). Could you check if that's a possibility?

**Comment by Mereck13579** [comment]
Okay, the sorting worked for the desktop app but the problem for the Android stay the same. It's not a problem of sorting for it but of Synchronization (or more of a limit of the synchronization options).

Comicrack desktop doesn't allow me to synchronize chapters by number but only by series (or alternative series, published, added, story arc or random). Since I have a limited space on my devices, I don't synchronize the full series but only the last X unread chapters (that will usually be around 20 since I synchronize a lot of series), leading to it synchronizing wrongly since I can't chose the "number" sorting method.

Right now, I switched the volume number back to undefined, having read the chapter 1 to 3 of the manga I mentioned earlier, it only pushed chapter 0 and chapters 18 up to 42. I guess if it hit the 93rd chapter it would've continued by synchronizing the correct chapters... but that'd be quite a waste of space...

**Comment by Deathspike** [comment]
I understand the problem. That is indeed something we can solve by making up a volume number. This should be labeled as an 'Advanced Feature' in the documentation (even if it really isn't complex to add). I presume that something along the lines of `--runnable.cli.metaUnknownVolume 99` would be a nice solution. Additional thoughts prior to implementation @Mike43110?

**Comment by Deathspike** [comment]
Supported since `4.0.9` (Mike seems to be GitHub shy and just talked to me via IM)

**Comment by Mike43110** [comment]
Shhhhh. :P
