### ISSUE TITLE
Ignore unrelated filetypes

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack#45]
Since I brought a Kindle I started using the sw "Kindle Comic Converter" (the project is hosted on github by the way) to optimize some of my cbz and conver them in compatible format (epub). Very good reading experience. 
The conversion is made into the same folder and, by logic, I'd like to keep the different format there.
I know that it is a bit in contrast with the semplification you're aiming to, but wouldn't be possible to set (by option or automatically) some filetypes to be ignored by comicrack, so that they are not renamed to "mrdel"?

Unrelated to my case but this would be useful also for: txt notes and memos, misc artwork and covers the user may like to keep all in one place.
Thanks!

**Comment by Deathspike** [comment]
That is an excellent point. The CLI should not touch files that do not belong to its control.

I'll add additional checks to ensure only `.cbz` and *temporary files* are altered.

**Comment by Deathspike** [comment]
Released in 4.0.10

**Comment by Deathspike** [comment]
This is actually in 4.0.11 due to a publish mistake.
