### ISSUE TITLE
error when saving to a network drive

### ISSUE THREAD

**Issue by jsravn** [Deathspike/mangarack#46]
Thanks for this great tool, saving me a lot of time.

I ran into this problem, though, when saving to my NAS:

```
$ mangarack-cli --component.core.batoto.username user --component.core.batoto.password pass http://bato.to/comic/_/comics/kingdom-r642
mangarack-cli (4.0.9)
Fetching Kingdom
Fetching Kingdom V02 #018.cbz
Finished Kingdom V02 #018.cbz (00:00:32)
Error: ENOTSUP: operation not supported on socket, write
    at Error (native)
```

It works fine when saving locally, but not to my NAS. Any ideas?

**Comment by Deathspike** [comment]
Initial search revealed nothing on worth on Google, so I'll need to dig deeper.

Could you please provide:

* Operating system (including 32/64-bits, and version)
* NodeJS version
* MangaRack version

And the way you mounted the NAS.

**Comment by jsravn** [comment]
```
$ uname -a
Linux odin 4.5.2-1-ARCH #1 SMP PREEMPT Thu Apr 21 18:21:27 CEST 2016 x86_64 GNU/Linux
```

```
$ node --version
v6.1.0
```

```
$ mangarack-cli --version
mangarack-cli (4.0.9)
```

NAS is mounted with gnome/gvfs as samba.

I tried digging into it but couldn't find what it is doing with so little stacktrace. It saves the volume correctly, then fails. Maybe it is trying to assign permissions (which would fail on my NAS)? There is a similar issue at https://github.com/atom/atom/issues/7651. Not a big deal, I will rsync stuff over afterwards.

**Comment by Deathspike** [comment]
That would make sense. There is some post-download checking going on, essentially, but that occurs *after* all the chapters. It wouldn't happen after a single chapter. I'll see if I can replicate this behavior by mounting my NAS under a Linux distribution I happen to have. I will come back to this later this week. For now, just rsync'ing things over will work fine indeed :+1:

**Comment by Deathspike** [comment]
If someone comes across this at a future date, and has the capability to determine the exact root cause, information would be very much appreciated. Otherwise, simply take the `rsync` approach.
