### ISSUE TITLE
Downloading a specific chapter

### ISSUE THREAD

**Issue by Maximilian-N** [Deathspike/mangarack#48]
It seems most of the switches were dropped in v4. Does that mean I always have to download all the chapters? One Piece for example has over 800....

**Comment by Deathspike** [comment]
This is exactly what it comes down to at this point. Sorry about that.

If you are one of the more technological advanced people (read: if you are a programmer), you might find it interesting to look at [the download service](https://github.com/Deathspike/mangarack/blob/master/mangarack-runnable-cli/src/services/downloadService.ts) that can be used for your own filter-capable CLI against the MR runtime.

**Comment by Deathspike** [comment]
Closing this due to lack of response. Feel free to open if more questions arise.

**Comment by murraypaul** [comment]
This is a pretty key piece of functionality, especially for very long series, where you might already have many years worth of collected volume files, but want to get newer single chapter files. 
mangarack won't see the existing volume files as matching the old chapters, so will redownload everything.
I tried to have a go at making the changes myself, but node expz-install fails on windows:

[npm-debug.zip](https://github.com/Deathspike/mangarack/files/311894/npm-debug.zip)

**Comment by Deathspike** [comment]
MangaRack does not see existing files as existing? That sounds like a bug. Can you confirm?

Also, I will test `ezpz-install` later. I develop on Windows too, so that should not be the issue.

**Comment by murraypaul** [comment]
I think I've identified my problem with the Windows install, or at least
I've gotten further. 

Lets take the example of Ah My Goddess.
Say I already have the first 44 volumes (chapters 001-281), as 44
single-volume files, and I want to get files from volume 45 onwards. 

However, the online sites have all single-chapter files. 

So mangarack will download everything starting from chapter 001, because
I don't have the chapter 001 file, even though I do have the *content*
for that file. 

On 2016-06-13 14:46, Roel van Uden wrote:

> MangaRack does not see existing files as existing? That sounds like a bug. Can you confirm? 
> 
> Also, I will test ezpz-install later. I develop on Windows too, so that should not be the issue. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/Deathspike/mangarack/issues/48#issuecomment-225585213
[2]
https://github.com/notifications/unsubscribe/AEKh6AHjKZjiectQL9nTis7atg3BhxX3ks5qLV9BgaJpZM4Ikr9P

**Comment by Deathspike** [comment]
Ah, yes, the idea would be to get those first 44 volumes through `mangarack` as well. 

I'm quite open to a good suggestion/pull for a good filter system. The one in `3.x` was horrid and unpredictable (two separate flags that would interact oddly on chapters with/without volume). It should be understandable and predictable. If it doesn't meet those requirements the suggestion/pull would be denied.

Please post follow-ups about `ezpz-install` in a separate issue for historic reasons.

**Comment by murraypaul** [comment]
I'm not a js programmer, but the following simple diff on downloadService.ts seems to work for what I need. Either or both of chapter and volume can be specified. It will still have the same issue for chapters with no volume specified. The simplest solution to that would be to only have a chapter flag. That would seem predictable.

This may be of use to the original poster, or others with the same requirement, until a better system is in place.

<       let lastExistingVolume = mio.settingService.getNumber('runnable.cli.skippast.volume');
<       let lastExistingChapter = mio.settingService.getNumber('runnable.cli.skippast.chapter');
<       let manualExistsVolume = chapter.volume.hasValue && lastExistingVolume > 0 && chapter.volume.value <= lastExistingVolume;
<       let manualExistsChapter = chapter.number.hasValue && lastExistingChapter > 0 && chapter.number.value <= lastExistingChapter;
<       if( !manualExistsVolume && !manualExistsChapter ) {
<         let chapterExists = await mio.promise<boolean>(callback => fs.exists(chapterPath.value, exists => callback(null, exists)));
<         if (chapterExists.hasValue && chapterExists.hasValue && !chapterExists.value) {
<           console.log(`Fetching ${chapterName.value}`);
<           let beginTime = Date.now();
<           let pages = await chapter.pagesAsync();
<           await downloadService.pagesAsync(provider, series, seriesPreviewImage, chapter, pages);
<           console.log(`Finished ${chapterName.value} ${prettyElapsedTime(beginTime)}`);
<         }
---
>       let chapterExists = await mio.promise<boolean>(callback => fs.exists(chapterPath.value, exists => callback(null, exists)));
>       if (chapterExists.hasValue && chapterExists.hasValue && !chapterExists.value) {
>         console.log(`Fetching ${chapterName.value}`);
>         let beginTime = Date.now();
>         let pages = await chapter.pagesAsync();
>         await downloadService.pagesAsync(provider, series, seriesPreviewImage, chapter, pages);
>         console.log(`Finished ${chapterName.value} ${prettyElapsedTime(beginTime)}`);

**Comment by murraypaul** [comment]
I've made a pull request which includes limiting by chapter number (single or from-to), but not volume.

**Comment by Deathspike** [comment]
Followed up in https://github.com/Deathspike/mangarack/issues/53
