### ISSUE TITLE
Batoto: Skip files with "DELETE" in chapter title.

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack#50]
I don't know if this already adressed but here we go.

As specified in batoto guide: https://bato.to/forums/topic/894-guide-to-uploading-editdeleteerrorsnotes/
if the user wants to delete a chapter he has to rename it with the tag "DELETE". This is actually a quite frequent occurrence.
Now, should the unlucky user run MangaRack while the chapter is still not deleted, since (see #2 leaving aside my suggestion about "v2") Mangarack will never download the chapter again if the filename stays the same, he will download without mistake a "corrupt"/"wrong" chapter.

Rephrasing: to skip files marked with "DELETE" will at least keep the user safe from downloading files that surely have something wrong.

**Comment by Deathspike** [comment]
The entire title is 'Delete'? What if a title of a chapter is actually 'Delete'?

Or does it also remove chapter/volume number?

**Comment by XellossMetallium** [comment]
If I recall correctly chapter and volume stays. The only difference is that
the entire word is in uppercase. When I see one in my rss I'll be more
precise.

Il Gio 16 Giu 2016, 00:30 Roel van Uden <notifications@github.com> ha
scritto:

**Comment by Deathspike** [comment]
https://github.com/Deathspike/mangarack/issues/79
