### ISSUE TITLE
Handling multiple copies of the same chapter/language/group combination

### ISSUE THREAD

**Issue by murraypaul** [Deathspike/mangarack#52]
There are some series where there are duplicate versions of the same chapter, which cannot be differentiated by language or group. An example is http://bato.to/comic/_/comics/terra-formars-r4747 chapters 161,162,170.
Currently I think mangarack will download the first one it finds (starting from the bottom of the list). In most cases I think this will be the oldest one rather than the newest. It will then skip the second, because a file with the same name will already exist.
How could this be handled better? 
Should the chapter list be processed before downloading to remove duplicates, keeping the last one uploaded by date?
If version identification can reliably identify the latest version, should that be used instead?
Should an option be added to add the chapter title to the filename, so that both files can be downloaded and the user then choose which one to use?
The last is very simple to implement, and the only one that will behave exactly the same regardless of when and how many times mangarack is run. The others will act differently if you have already downloaded the older version versus starting from scratch.

**Comment by Deathspike** [comment]
https://github.com/Deathspike/mangarack/issues/79
