### ISSUE TITLE
command just seems to hang on ubuntu

### ISSUE THREAD

**Issue by ptempier** [Deathspike/mangarack#60]
orogor@pascalou:~$ mangarack-cli 
mangarack-cli (4.0.11)
^C
orogor@pascalou:~$ mangarack-cli -h
mangarack-cli (4.0.11)
^C
orogor@pascalou:~$ mangarack-cli -V
mangarack-cli (4.0.11)
^C

**Comment by Deathspike** [comment]
You need to provide series addresses or stdin with series addresses. Right now it is just waiting for you to provide it with instructions... Which you don't. Refer to the readme. :/

**Comment by yanandcoffee** [comment]
Might want to update the README or build a small site for MangaRack to say what all the valid series addresses would be. This happened to me before I looked into the src code 😉 .
