### ISSUE TITLE
Everything I download from Kissmanga is just the cover + info

### ISSUE THREAD

**Issue by ostiniatoze** [Deathspike/mangarack#65]
As title, I get no error code or anything, the program runs normally. I believe it started over the weekend; if I download anything older the same thing happens.
Mangafox doesn't work (though I could never get that working) and Batoto works as normal.

Thank you for your time.

edit: http://forum.kissanime.com/index.php?threads/%E3%83%BBupdate-kiss-anime-server-error-runtime-error-%E3%80%8C12-march-2017%E3%80%8D.1223/ <- seems they had an error last week, may have something to do with it, could have changed something.

**Comment by Deathspike** [comment]
Fixed in 4.1.0. KissManga/MangaFox are now functional.
