### ISSUE TITLE
Mangarack fails to lunch

### ISSUE THREAD

**Issue by Mereck13579** [Deathspike/mangarack#67]
Using mangarack returns me an error and refuse to lunch : 
```
root@mangarack:/home/mangarack# mangarack-cli
/usr/bin/env: 'node\r': No such file or directory
root@mangarack:/home/mangarack#
```

EDIT: forgot to mention that I just updated mangarack

**Comment by Mereck13579** [comment]
Herm... fixed quickly by converting the code linebreak from dos type to unix type. (:set ff=unix in vim)

**Comment by Deathspike** [comment]
Damn. I did that again, huh? Looks like this problem has been in `npm` since forever.

I pushed out 4.1.1 to fix this for everyone, but yeah, that's it. Just convert line endings...

**Comment by Mereck13579** [comment]
Haha yes, happens to me quite often as well.

**Comment by Deathspike** [comment]
The bane of being a Windows developer haha. :-3
